version: 2.1
orbs:
  node: circleci/node@3.0.0
jobs:
  build:
    executor:
      name: node/default
      tag: '13.12'
    steps:
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --immutable
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
  lighthouseci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: yarn && yarn add -g @lhci/cli@0.4.x
      - run: yarn build
      - run: lhci autorun
workflow:
  me:
    jobs:
      - build
